name: Server Smoke Tests

on:
    # Run on pushes to any branch. Not triggered for forked repo PRs.
  push:
  schedule:
    # Run once a day at 9AM PDT (16 UTC) on week days (1-5).
    # Last commit on default branch.
    # https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule
    - cron:  '0 16 * * 1-5'

jobs:
  smoke:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    # Smoke tests do own install
    - name: Run Smoke Tests
      run: npm run smoke
      env:
        TEST_LICENSE: ${{ secrets.TEST_LICENSE }}
